services:
  - type: web
    name: SoilScout
    env: python
    pythonVersion: 3.11.9
    plan: free
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      bash start.sh
    envVars:
      - key: PORT
        value: "10000"
      - key: EE_PRIVATE_KEY
        sync: false
