services:
  - type: web
    name: soil-crop-scout
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      bash start.sh
    envVars:
      - key: PORT
        value: "10000"
      # Put your GOOGLE EARTH ENGINE service-account JSON in this env var
      - key: EE_PRIVATE_KEY
        sync: false
