services:
  - type: web
    name: soil-moisture-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.enableCORS=false
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: OPENAI_API_KEY
        sync: false
      - key: EE_PRIVATE_KEY
        sync: false
